"""Stable subprocess boundary for the AIQ side of the AIQ->Flow
Xray demo:

    python -m aiq.demo --status completed --output trace.json
    python -m aiq.demo --status active    --output trace.json

This module drives the fake reference chat agent (no real LLM, no real MCP,
no network) and writes exactly one schema-v1 domain-event-history JSON
document, produced through AIQ's real exporter (`TraceService` /
`trace_to_json`) -- never hand-assembled. It does not import Flow Xray and
does not start an HTTP server; combining this output into an HTML view is
Flow Xray's responsibility, not this module's.

Works from an installed package (no `PYTHONPATH` needed) and from any
working directory.

Canonical event sequences (fixed; also asserted by tests):

    completed (9 nodes / 8 edges / 1 root, terminal_status="completed"):
        UserMessageAdded
        ModelCallRequested
        ModelCallSucceeded
        ToolCallRequested
        ToolCallSucceeded
        ModelCallRequested
        ModelCallSucceeded
        AnswerProduced
        RunCompleted

    active (4 nodes / 3 edges / 1 root, terminal_status="active"):
        UserMessageAdded
        ModelCallRequested
        ModelCallSucceeded
        ToolCallRequested   <- stops here: request committed, persisted
                                explicit operation_id, effect not yet run,
                                no terminal event anywhere in the stream.

Event IDs, the run ID, the agent name, the causal structure and the
payloads are all deterministic (uuid5-derived) across repeated runs.
`created_at` is the one field that stays wall-clock: it is generated by the
event store itself, and making it reproducible would mean changing store
internals, which is out of scope here.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
import tempfile
import uuid
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any

from .core import Event, InMemoryEventStore
from .runtime import (
    AgentDefinition,
    DurableDispatcher,
    DurableEffectDispatcher,
    EffectContext,
    EffectRegistry,
    effect_request,
)
from .streams import run_stream_id
from .trace import TraceService, trace_to_json

_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_URL, "aiq.demo")
_AGENT_NAME = "demo-assistant"

__all__ = [
    "generate_completed_trace",
    "generate_active_trace",
    "write_trace_json",
    "main",
]


def _deterministic_id(*parts: str) -> uuid.UUID:
    return uuid.uuid5(_NAMESPACE, ":".join(parts))


@dataclass(frozen=True)
class _DemoState:
    messages: tuple[str, ...] = ()
    answer: str | None = None
    completed: bool = False


def _build_agent() -> AgentDefinition[_DemoState]:
    agent = AgentDefinition(
        _AGENT_NAME,
        initial_state=_DemoState,
        terminal_event_types={"RunCompleted"},
    )

    @agent.reducer
    def evolve(state: _DemoState, event: Event) -> _DemoState:
        if event.event_type == "UserMessageAdded":
            return replace(state, messages=state.messages + (str(event.data["text"]),))
        if event.event_type == "ToolCallSucceeded":
            return replace(state, messages=state.messages + ("tool-result",))
        if event.event_type == "AnswerProduced":
            return replace(state, answer=str(event.data["text"]))
        if event.event_type == "RunCompleted":
            return replace(state, completed=True)
        return state

    @agent.react("UserMessageAdded")
    def request_model(event: Event, state: _DemoState):
        return [
            effect_request(
                "ModelCallRequested",
                {"call_id": "model-call-1"},
                {"causation_id": str(event.event_id)},
                event_id=_deterministic_id("ModelCallRequested:1", str(event.event_id)),
            )
        ]

    @agent.react("ModelCallSucceeded")
    def interpret_model(event: Event, state: _DemoState):
        response = event.data["response"]
        if response["type"] == "tool_call":
            tool_call = response["tool_call"]
            return [
                effect_request(
                    "ToolCallRequested",
                    {
                        "call_id": tool_call["id"],
                        "tool": tool_call["name"],
                        "arguments": tool_call["arguments"],
                    },
                    {"causation_id": str(event.event_id)},
                    event_id=_deterministic_id("ToolCallRequested", str(event.event_id)),
                )
            ]
        return [
            Event(
                "AnswerProduced",
                {"text": response["text"]},
                {"causation_id": str(event.event_id)},
                event_id=_deterministic_id("AnswerProduced", str(event.event_id)),
            ),
            Event(
                "RunCompleted",
                {},
                {"causation_id": str(event.event_id)},
                event_id=_deterministic_id("RunCompleted", str(event.event_id)),
            ),
        ]

    @agent.react("ToolCallSucceeded")
    def continue_after_tool(event: Event, state: _DemoState):
        return [
            effect_request(
                "ModelCallRequested",
                {"call_id": "model-call-2"},
                {"causation_id": str(event.event_id)},
                event_id=_deterministic_id("ModelCallRequested:2", str(event.event_id)),
            )
        ]

    return agent


class _DeterministicFakeLLM:
    """Instant in-process fake. No network, no real model, deterministic
    per fresh instance: the tool-call/answer branch depends only on call
    count, not on wall-clock or randomness."""

    def __init__(self) -> None:
        self._calls = 0

    async def respond(self, messages: tuple[str, ...], operation_id: str) -> dict[str, Any]:
        self._calls += 1
        if self._calls == 1:
            return {
                "type": "tool_call",
                "tool_call": {
                    "id": "pressure-A-17-24h",
                    "name": "get_well_pressure",
                    "arguments": {"well_id": "A-17", "hours": 24},
                },
            }
        return {"type": "answer", "text": "A-17 pressure is available (demo)."}


class _DeterministicFakeMCP:
    async def call(self, *, tool: str, arguments: dict, operation_id: str) -> dict[str, Any]:
        return {"well_id": arguments.get("well_id", "A-17"), "pressure": 152.4, "unit": "bar"}


def _build_effects() -> EffectRegistry[_DemoState]:
    effects = EffectRegistry[_DemoState]()

    @effects.effect("ModelCallRequested")
    async def call_model(event: Event, state: _DemoState, context: EffectContext):
        response = await context.require("llm").respond(
            state.messages,
            operation_id=str(event.event_id),
        )
        return [
            Event(
                "ModelCallSucceeded",
                {"call_id": event.data["call_id"], "response": response},
                event_id=_deterministic_id("ModelCallSucceeded", str(event.event_id)),
            )
        ]

    @effects.effect("ToolCallRequested")
    async def call_tool(event: Event, state: _DemoState, context: EffectContext):
        result = await context.require("mcp").call(
            tool=event.data["tool"],
            arguments=dict(event.data["arguments"]),
            operation_id=str(event.event_id),
        )
        return [
            Event(
                "ToolCallSucceeded",
                {
                    "call_id": event.data["call_id"],
                    "tool": event.data["tool"],
                    "result": result,
                },
                event_id=_deterministic_id("ToolCallSucceeded", str(event.event_id)),
            )
        ]

    return effects


def _first_event(run_id: str) -> Event:
    return Event(
        "UserMessageAdded",
        {"text": "Pressure for A-17"},
        event_id=_deterministic_id("UserMessageAdded", run_id),
    )


def _build_dispatchers(
    agent: AgentDefinition[_DemoState],
    store: InMemoryEventStore,
) -> tuple[DurableDispatcher[_DemoState], DurableEffectDispatcher[_DemoState]]:
    reactions = DurableDispatcher(
        agent=agent, store=store, subscription_name=f"{_AGENT_NAME}:reactions"
    )
    effects_worker = DurableEffectDispatcher(
        agent=agent,
        store=store,
        effects=_build_effects(),
        context=EffectContext(
            {"llm": _DeterministicFakeLLM(), "mcp": _DeterministicFakeMCP()}
        ),
        subscription_name=f"{_AGENT_NAME}:effects",
    )
    return reactions, effects_worker


async def generate_completed_trace() -> dict[str, Any]:
    """Drives the reference chat flow all the way to RunCompleted.

    Produced via `TraceService.export()` + `trace_to_json()` -- the real
    exporter, not a hand-built document.
    """
    store = InMemoryEventStore()
    agent = _build_agent()
    run_id = "completed-demo-run"
    await store.append(run_stream_id(_AGENT_NAME, run_id), -1, [_first_event(run_id)])

    reactions, effects_worker = _build_dispatchers(agent, store)
    for _ in range(30):
        reaction_progress = await reactions.run_once()
        effect_progress = await effects_worker.run_once()
        if not reaction_progress and not effect_progress:
            break
    else:
        raise RuntimeError("completed-demo-run did not reach a stable checkpoint")

    service = TraceService(store=store, agents={_AGENT_NAME: agent})
    trace = await service.export(_AGENT_NAME, run_id)
    return trace_to_json(trace)


async def generate_active_trace() -> dict[str, Any]:
    """Stops mid-flight, right after a ToolCallRequested is committed but
    before its effect handler runs -- a realistic non-terminal snapshot
    with a persisted, unresolved effect request that still carries an
    explicit operation_id.
    """
    store = InMemoryEventStore()
    agent = _build_agent()
    run_id = "active-demo-run"
    stream_id = run_stream_id(_AGENT_NAME, run_id)
    await store.append(stream_id, -1, [_first_event(run_id)])

    reactions, effects_worker = _build_dispatchers(agent, store)
    # Reaction and effect checkpoints advance independently over the shared
    # global log, so a fixed call count doesn't reliably land at a given
    # point in the flow. Instead: alternate reactions/effects, and stop the
    # instant ToolCallRequested is committed -- deliberately skipping the
    # effects round that would resolve it, so the run has no terminal event.
    for _ in range(10):
        await reactions.run_once()
        history = await store.load(stream_id)
        if any(envelope.event.event_type == "ToolCallRequested" for envelope in history):
            break
        await effects_worker.run_once()
    else:
        raise RuntimeError("active-demo-run did not reach the expected mid-flight state")

    service = TraceService(store=store, agents={_AGENT_NAME: agent})
    trace = await service.export(_AGENT_NAME, run_id)
    return trace_to_json(trace)


def write_trace_json(document: dict[str, Any], destination: Path, *, pretty: bool = True) -> None:
    """Atomically write `document` to `destination`.

    Writes to a temporary file in the destination's own directory, then
    `os.replace()`s it into place -- so a failure partway through never
    leaves a partial or corrupt file at `destination`, and an existing
    file at `destination` is replaced only once the new one is fully
    written.
    """
    destination = Path(destination)
    destination.parent.mkdir(parents=True, exist_ok=True)

    fd, tmp_name = tempfile.mkstemp(
        dir=str(destination.parent),
        prefix=f".{destination.name}.",
        suffix=".tmp",
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            if pretty:
                json.dump(document, handle, indent=2, sort_keys=True)
            else:
                json.dump(document, handle, separators=(",", ":"), sort_keys=True)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_name, destination)
    except BaseException:
        try:
            os.unlink(tmp_name)
        except FileNotFoundError:
            pass
        raise


_GENERATORS = {
    "completed": generate_completed_trace,
    "active": generate_active_trace,
}


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="python -m aiq.demo",
        description=(
            "Generate one AIQ schema-v1 domain-event-history JSON "
            "document from the fake reference chat agent (no real LLM/MCP, "
            "no network). This produces AIQ JSON only -- rendering it "
            "as HTML is Flow Xray's job, not this command's."
        ),
    )
    parser.add_argument(
        "--status",
        required=True,
        choices=sorted(_GENERATORS),
        help="Which canonical run to generate.",
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Path to write the trace JSON document to.",
    )
    pretty_group = parser.add_mutually_exclusive_group()
    pretty_group.add_argument(
        "--pretty",
        action="store_true",
        default=True,
        help="Write indented, readable JSON (default).",
    )
    pretty_group.add_argument(
        "--compact",
        action="store_true",
        help="Write compact JSON instead of indented.",
    )
    return parser.parse_args(argv)


async def _run(args: argparse.Namespace) -> dict[str, Any]:
    generator = _GENERATORS[args.status]
    return await generator()


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    try:
        document = asyncio.run(_run(args))
        write_trace_json(document, args.output, pretty=not args.compact)
    except Exception as error:  # noqa: BLE001 - CLI boundary, report and exit non-zero
        print(f"aiq.demo: error: {error}", file=sys.stderr)
        return 1

    print(f"output={args.output}")
    print(f"status={document['terminal_status']}")
    print(f"nodes={len(document['nodes'])}")
    print(f"edges={len(document['edges'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
